apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-ygej
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-ygej
    app.kubernetes.io/part-of: test-app-rhab
  name: maven-hello-world-ygejvufp
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: maven-hello-world-ygej
    weight: null
status: {}
